-- 코드를 입력하세요 
# 2022년 1월 기준
# 저자 별, 카테고리별
# 매출액(판매량 * 판매가)

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES*B.PRICE) AS TOTAL_SALES
FROM BOOK AS B JOIN AUTHOR AS A JOIN BOOK_SALES AS S
    ON B.AUTHOR_ID = A.AUTHOR_ID AND B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE LIKE '2022-01-%'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;