-- 코드를 입력하세요
SELECT *
FROM (SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
      FROM ONLINE_SALE
      UNION ALL
      SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT -- NULL AS 컬럼명
      FROM OFFLINE_SALE) AS SALE -- 서브쿼리 쓸 때 ALIAS 꼭 만들어주기
WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;