-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM (SELECT O.ANIMAL_ID, O.NAME, DATEDIFF(O.DATETIME, I.DATETIME)+1 AS DURATION
      FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID) AS INAOUT
ORDER BY DURATION DESC
LIMIT 2
;