-- 코드를 입력하세요

-- 세단/SUV 
-- 2022-11-01~2022-11-30 대여 가능
-- 30일 대여 금액 50만 이상 200만 미만


SELECT CAR_ID, CAR.CAR_TYPE, DAILY_FEE*30*PAY AS FEE
FROM (SELECT CAR_ID, CAR_TYPE, DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_ID NOT IN (SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01' OR START_DATE IS NULL) AND CAR_TYPE IN('세단', 'SUV')) AS CAR
LEFT JOIN
(SELECT CAR_TYPE, (100-DISCOUNT_RATE)/100 AS PAY
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE DURATION_TYPE LIKE '30일%') AS DIS
ON CAR.CAR_TYPE = DIS.CAR_TYPE
WHERE DAILY_FEE*30*PAY >= 500000 AND DAILY_FEE*30*PAY < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;