-- 코드를 입력하세요
-- 즐겨찾기 수가 같은 식당이 나올 수 있음
# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
# FROM (
#     SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
#            ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC, REST_ID ASC) as rn
#     FROM REST_INFO
# ) SUB
# WHERE rn = 1
# ORDER BY FOOD_TYPE DESC;

SELECT FOOD_TYPE,REST_ID,REST_NAME,FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE,FAVORITES) IN (SELECT FOOD_TYPE,MAX(FAVORITES)
                                FROM REST_INFO
                                GROUP BY FOOD_TYPE)
ORDER BY FOOD_TYPE DESC;
