-- 코드를 입력하세요
# 년, 월, 성별 별 -> 묶을 기준
# 상품 구매한 회원 수 -> 집계할 것
# 년, 월, 성별 오름차순
# 성별 정보 IS NOT NULL

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT USER_ID) AS USERS
FROM USER_INFO NATURAL JOIN ONLINE_SALE
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER;