-- 코드를 입력하세요
SELECT HISTORY_ID, CAR_ID, START_DATE, END_DATE, 
    CASE
        WHEN DATEDIFF(END_DATE, START_DATE) >= 29 THEN '장기 대여'
        -- DATEDIFF(큰, 작): 날짜 차이 계산, +1 해줘야 함
        ELSE '단기 대여'
        END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, '%Y-%m') = '2022-09'
ORDER BY HISTORY_ID DESC
;