-- 코드를 입력하세요
/* CASE WHEN THEN ELSE END AS
MAX 쓰면 대여 가능/대여중 둘 다 있을 때 더 큰 대여중을 선택 */

/* 서브 쿼리 방법
SELECT DISTINCT CAR_ID,
    CASE
        WHEN CAR_ID IN (
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE)
        THEN '대여중'
        ELSE '대여 가능' END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC;
*/

SELECT CAR_ID, 
    MAX(CASE 
        WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN '대여중'
        ELSE '대여 가능' END) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;

