-- 코드를 입력하세요

-- 생산일자 2022-05
-- 식품ID, 식품 이름, 총매출
-- 총매출 내림, 식품 ID 오름

SELECT PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT*PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT NATURAL JOIN FOOD_ORDER
WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC
;