-- 코드를 입력하세요

SELECT APNT_NO, PT_NAME, P.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM (SELECT *
      FROM APPOINTMENT
      WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND APNT_CNCL_YN = 'N' AND MCDP_CD = 'CS' 
      ) A
      JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
      JOIN PATIENT P ON A.PT_NO = P.PT_NO
ORDER BY APNT_YMD
;
