-- 코드를 입력하세요
-- 재귀 CTE: 표에 없는 기준 만드려면 WITH RECURSIVE 표이름 AS () 으로 가DB 먼저 만들어주기\

WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23)
SELECT HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM HOURS H LEFT JOIN ANIMAL_OUTS A ON H.HOUR = HOUR(A.DATETIME)
GROUP BY HOUR
;