-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH) = '3' AND GENDER = 'W' AND TLNO IS NOT NULL 
-- 날짜 특정 영역 추출: YEAR(), MONTH(), DAYOFMONTH()
-- 결측 제외 IS NOT NULL
ORDER BY MEMBER_ID ASC;