-- 코드를 입력하세요
# 완료 중고 거래 총금액 70이상인
# 회원ID, 닉네임, 총거래금액
# 총거래금액 오름차순
SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS B JOIN USED_GOODS_USER AS U
    ON B.WRITER_ID = U.USER_ID
WHERE STATUS = 'DONE'
GROUP BY U.USER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;
