-- 코드를 입력하세요
-- 리뷰 가장 많이 작성한 회원의 리뷰
SELECT MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
FROM MEMBER_PROFILE P RIGHT JOIN REST_REVIEW RE
ON P.MEMBER_ID = RE.MEMBER_ID
WHERE RE.MEMBER_ID IN (SELECT MEMBER_ID
FROM (SELECT MEMBER_ID, RANK() OVER (ORDER BY COUNT(*) DESC) AS R_RANK
    FROM REST_REVIEW
    GROUP BY MEMBER_ID) AS R
WHERE R_RANK = 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT
;