-- 코드를 작성해주세요
-- RARE인 아이템의 (PARENT_ITEM_ID이고)
-- 강화VER 아이템 (ITEM_ID인 값)

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO NATURAL JOIN ITEM_TREE
WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID 
                 FROM ITEM_INFO
                 WHERE RARITY = 'RARE')
ORDER BY ITEM_ID DESC
;