-- 코드를 입력하세요
SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_CAR NATURAL JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_TYPE = '세단' AND DATE_FORMAT(START_DATE, '%Y-%m') = '2022-10'
ORDER BY CAR_ID DESC;