-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM (SELECT *, RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS L
      FROM FISH_INFO) AS A NATURAL JOIN FISH_NAME_INFO AS B
WHERE L = 1
ORDER BY ID
;